# Generated by Django 5.2.7 on 2025-11-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Espetaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao', models.IntegerField()),
                ('classificacao', models.CharField(choices=[('Livre', 'Classificacao Livre'), ('+10', 'Classificacao 10'), ('+12', 'Classificacao 12'), ('+14', 'Classificacao 14'), ('+16', 'Classificacao 16'), ('+18', 'Classificacao 18')], max_length=5)),
                ('categoria', models.CharField(choices=[('Comédia', 'Comedia'), ('Drama', 'Drama'), ('Musical', 'Musical'), ('Dança', 'Danca'), ('Tragédia', 'Tragedia')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teatro', to='app.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espetaculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='app.espetaculo')),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='app.teatro')),
            ],
        ),
    ]
