# Generated by Django 5.2.7 on 2025-12-02 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
